// Aria's general security guidance (Task 81).
//
// Fixed educational content written for each classification, plus one key
// defence per sub-type. It is NOT generated by a model or the backend and never
// refers to the specific prompt. Task 82 will add guidance from
// POST /api/avatar-guide (whose response shape is not yet documented beyond the
// SDS §6.5 `avatarFeedback` string) — see hooks/useAriaGuidance.js.
//
// Every guidance object has the same shape, whatever its source:
//   { source, scope, summary, whyTitle, why, nextSteps[], do[], dont[], keyDefence }

const CLASS_GUIDANCE = {
  Safe: {
    summary: 'PromptShield did not match this prompt to a supported prompt-injection class.',
    whyTitle: 'Why good habits still matter',
    why: 'Clear, well-structured prompts behave more predictably and make real injection attempts easier to spot — for you and for the systems you build.',
    nextSteps: [
      'Send the prompt as intended.',
      'Check it again if you later add documents, web content or tool output to the conversation.',
    ],
    do: [
      'State the task and the output you expect',
      'Keep your instructions separate from any content you supply',
      'Review AI output before acting on it',
    ],
    dont: [
      'Paste passwords, API keys or other secrets into prompts',
      'Treat a Safe result as cover for every kind of risk',
      'Ask the model to set aside its own rules',
    ],
  },
  'Direct Jailbreak': {
    summary: 'Prompts in this class try to override the model’s instructions, role or policies.',
    whyTitle: 'Why it’s dangerous',
    why: 'A successful override can bypass safeguards, expose protected instructions or produce output nobody intended.',
    nextSteps: [
      'Don’t send the prompt to a production model as written.',
      'Rewrite it to state only the task you need.',
      'Test your AI features against this pattern before release.',
    ],
    do: [
      'State the task in plain terms',
      'Keep system instructions private and fixed',
      'Test against known jailbreak patterns',
    ],
    dont: [
      'Ask a model to ignore its instructions',
      'Let any persona override safety rules',
      'Reframe or split a refused request',
    ],
  },
  'Indirect Injection': {
    summary: 'Prompts in this class carry instructions inside content an AI system consumes, rather than as a direct request.',
    whyTitle: 'Why it’s dangerous',
    why: 'A system that follows embedded instructions can be steered by whoever wrote the content — leaking data or taking actions its user never asked for.',
    nextSteps: [
      'Treat the content as data to analyse, not as instructions to follow.',
      'Check which parts of the input came from outside sources before relying on the output.',
      'Require confirmation before an AI agent acts on external content.',
    ],
    do: [
      'Keep your instructions separate from external content',
      'Tell the model explicitly to treat supplied content as data',
      'Confirm any action an agent proposes from tool or web results',
    ],
    dont: [
      'Follow instructions found inside documents, web pages or tool output',
      'Give untrusted content the same authority as the user',
      'Let an agent change data without review',
    ],
  },
}

// One key defence per sub-type, keyed by the sub-type names in config/detection.js.
const SUBTYPE_DEFENCES = {
  'Policy Evasion': 'Judge a request by what it ultimately asks for, not by how it is framed or split up.',
  'Multi-Turn Manipulation':
    'Evaluate the conversation as a whole — a harmless-looking turn can be one step toward a restricted request.',
  'Role Override': 'Keep the model’s assigned role fixed, and treat requests to switch tasks mid-prompt as untrusted.',
  'Persona Hijacking': 'No persona, however it is framed, should override the model’s safety rules.',
  'System Prompt Overwrite': 'Treat system instructions as confidential and fixed — never echo or replace them on request.',
  'Document Embedding': 'Treat text inside documents, emails and pasted files as content to analyse, never as instructions.',
  'Web Content Injection': 'Assume retrieved web content may contain planted instructions — summarise it, don’t obey it.',
  'Tool Output Injection': 'Validate tool and API results before an agent acts on them, especially actions that change data.',
}

// General guidance for an analysis result, or null if the class is unknown.
export function getGeneralGuidance({ classification, subtype }) {
  const base = CLASS_GUIDANCE[classification]
  if (!base) return null
  const defence = subtype ? SUBTYPE_DEFENCES[subtype] : undefined

  return {
    source: 'general',
    scope: defence ? subtype : classification,
    ...base,
    keyDefence: defence ? { subtype, text: defence } : null,
  }
}
