// Detection taxonomy from frontend/TASKS.md: 3 classes, 8 sub-types.
// `label` values match the API's `classification` strings exactly.
//
// `explanation` is fixed educational text about what a classification means.
// It is NOT generated by the model and must stay category-level: it describes
// the classes PromptShield checks for, never the specific prompt.
export const DETECTION_CLASSES = [
  {
    label: 'Safe',
    variant: 'safe',
    description: 'No supported prompt-injection attack detected.',
    subtypes: [],
    explanation: {
      title: 'Why this is classified Safe',
      points: [
        'PromptShield did not classify the prompt as a Direct Jailbreak — an attempt to override the model’s instructions, role or policies.',
        'It was not classified as an Indirect Injection — an instruction hidden in documents, web content or tool output.',
      ],
      caveat:
        'A Safe result covers these prompt-injection classes only. It is not a guarantee that the prompt is harmless in every other respect.',
    },
  },
  {
    label: 'Direct Jailbreak',
    variant: 'danger',
    description: 'The user tries to override the model directly.',
    subtypes: ['Policy Evasion', 'Multi-Turn Manipulation', 'Role Override', 'Persona Hijacking', 'System Prompt Overwrite'],
    subtypeNoun: 'attack patterns',
    // Fixed definitions of each attack pattern — educational, not model output.
    subtypeDefinitions: {
      'Policy Evasion':
        'Tries to obtain output the model’s policies would refuse, often by rephrasing, reframing or splitting the request.',
      'Multi-Turn Manipulation':
        'Builds toward a restricted request gradually over several conversation turns rather than asking directly.',
      'Role Override': 'Instructs the model to abandon its assigned role or task and follow new instructions instead.',
      'Persona Hijacking':
        'Asks the model to adopt an alternative persona, such as “DAN”, that claims to be free of its usual rules.',
      'System Prompt Overwrite': 'Attempts to ignore, replace or reveal the model’s underlying system instructions.',
    },
    explanation: {
      title: 'What this classification means',
      points: [
        'The prompt was classified as a direct attempt to override or bypass the model’s instructions, role or policies.',
        'Direct attacks are written into the prompt itself, unlike indirect injections hidden in external content.',
      ],
      caveat: 'This classifies the prompt’s pattern. It is not a judgement of the sender’s intent.',
    },
  },
  {
    label: 'Indirect Injection',
    variant: 'warning',
    description: 'A malicious instruction hides in embedded content.',
    subtypes: ['Document Embedding', 'Web Content Injection', 'Tool Output Injection'],
    subtypeNoun: 'injection vectors',
    // Fixed definitions of each injection vector — educational, not model output.
    subtypeDefinitions: {
      'Document Embedding':
        'Instructions hidden inside a document, such as a file, email or pasted text, that an AI system is asked to read.',
      'Web Content Injection': 'Instructions planted in web pages or online content that an AI system retrieves or browses.',
      'Tool Output Injection': 'Instructions placed in the results returned by a tool, plugin or API that an AI agent calls.',
    },
    explanation: {
      title: 'What this classification means',
      points: [
        'Indirect injection describes instructions that arrive through embedded or external content — documents, web pages or tool output — rather than from the user’s own request.',
        'AI systems should treat such content as data to analyse, not as instructions to follow.',
      ],
      caveat: 'This classifies the input’s pattern. It does not identify where the content came from or who wrote it.',
    },
    // General illustration of the attack path — not a trace of any analysis.
    concept: {
      title: 'How indirect injection works',
      steps: [
        { title: 'Untrusted content', text: 'A document, web page or tool result' },
        { title: 'AI context', text: 'The model reads it with the user’s request' },
        { title: 'Embedded instruction', text: 'Hidden text may be followed as a command' },
      ],
    },
  },
]

export function findDetectionClass(label) {
  return DETECTION_CLASSES.find((detection) => detection.label === label)
}

// The class a sub-type belongs to, e.g. 'Persona Hijacking' → Direct Jailbreak.
export function findClassForSubtype(subtype) {
  return DETECTION_CLASSES.find((detection) => detection.subtypes.includes(subtype))
}
